import { Document, Page, Text, View, StyleSheet } from "@react-pdf/renderer";
import type { AuditResult } from "./types";

// Styles for the PDF document - using StyleSheet.create for performance
const styles = StyleSheet.create({
  page: { padding: 30, fontSize: 11, fontFamily: "Helvetica" },
  header: { fontSize: 24, fontWeight: "bold", marginBottom: 8, color: "#101114" },
  subHeader: { fontSize: 12, color: "#5f6673", marginBottom: 20 },
  savings: { fontSize: 18, color: "#127a52", marginBottom: 10, fontWeight: "bold" },
  meta: { fontSize: 10, color: "#5f6673", marginBottom: 8 },
  sectionTitle: { fontSize: 14, fontWeight: "bold", marginTop: 20, marginBottom: 10, color: "#101114" },
  row: { flexDirection: "row", justifyContent: "space-between", marginBottom: 6, paddingBottom: 6, borderBottom: "1px solid #d9dee8" },
  label: { fontWeight: "bold", color: "#101114" },
  value: { color: "#101114" },
  positive: { color: "#127a52" },      // Green for savings
  warning: { color: "#d89a22" },       // Orange for no savings / increase
  reason: { fontSize: 9, color: "#5f6673", marginTop: 2 },
  summary: { marginTop: 20, fontSize: 11, lineHeight: 1.6, color: "#101114" },
  footer: { marginTop: 30, fontSize: 9, color: "#5f6673", textAlign: "center" },
});

/**
 * PDF component for the audit report.
 * Renders a single A4 page with header, metadata, savings summary, per-tool recommendations, and footer.
 *
 * @param audit - The audit result containing team size, use case, tool lines, savings, and summary
 */
export function AuditPDF({ audit }: { audit: AuditResult }) {
  return (
    <Document>
      <Page size="A4" style={styles.page}>
        {/* Header section */}
        <Text style={styles.header}>SpendLens AI — Audit Report</Text>
        <Text style={styles.subHeader}>
          Generated on {new Date(audit.createdAt).toLocaleDateString()}
        </Text>

        {/* Metadata: team size, use case, tools reviewed, current spend */}
        <Text style={styles.meta}>
          Team Size: {audit.teamSize} people | Primary Use Case: {audit.useCase}
        </Text>
        <Text style={styles.meta}>
          Tools Reviewed: {audit.lines.length} | Total Current Spend: ${audit.totalCurrent.toLocaleString()}/mo
        </Text>

        {/* Savings highlight */}
        <Text style={styles.savings}>
          ${audit.monthlySavings.toLocaleString()}/mo savings | ${audit.annualSavings.toLocaleString()}/yr
        </Text>

        {/* Per-tool recommendations table */}
        <Text style={styles.sectionTitle}>Recommendations</Text>
        {audit.lines.map((line) => (
          <View key={line.id} style={styles.row}>
            <View>
              <Text>
                <Text style={styles.label}>{line.toolName}:</Text> {line.action}
              </Text>
              <Text style={styles.reason}>{line.reason}</Text>
            </View>
            <Text style={line.savings > 0 ? styles.positive : styles.warning}>
              ${line.savings}/mo
            </Text>
          </View>
        ))}

        {/* AI-style summary from the audit engine */}
        <Text style={styles.summary}>{audit.summary}</Text>

        {/* Footer */}
        <Text style={styles.footer}>
          Generated by SpendLens AI — {new Date().toLocaleDateString()}
        </Text>
      </Page>
    </Document>
  );
}
